name: Generate gitartwork
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: write
jobs:
  generate-gitartwork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: jasineri/gitartwork@v1
        with:
          user_name: 'ShotaHayashi0601'
          text: 'SHCodeLv'
          animation: true

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # repo スコープ必須

          filename: metrics.svg
          #base: 'repositories'
          base: 'user'

          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          # indepthで詳細解析。ただし200リポジトリ以上あると時間はかかる
          plugin_languages_indepth: no

          # HTML/CSSを除外しない場合はここを消すか空にする
          plugin_languages_ignored: ''

      - name: Push generated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add gitartwork.svg metrics.svg
          git commit -m "Update gitartwork & Metrics"

          # 競合を無視して強制プッシュ
          git push --force https://ShotaHayashi0601:${{ secrets.METRICS_TOKEN }}@github.com/ShotaHayashi0601/ShotaHayashi0601.git
